import { GoogleGenAI } from "@google/genai";
import { ImageData, GeneratedResult } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Edits an image based on a text prompt using Gemini 2.5 Flash Image.
 * 
 * @param originalImage The source image data (base64 and mimeType)
 * @param prompt The text instruction for editing (e.g., "Change colors to orange and red")
 * @returns The generated image or text response
 */
export const editImageWithGemini = async (
  originalImage: ImageData,
  prompt: string
): Promise<GeneratedResult> => {
  try {
    // Clean base64 string if it contains the data URL prefix
    const cleanBase64 = originalImage.base64.split(',')[1] || originalImage.base64;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: originalImage.mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      // Note: responseMimeType is not supported for nano banana models
    });

    let generatedImageUrl: string | undefined;
    let generatedText: string | undefined;

    // Iterate through parts to find image and text
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64EncodeString = part.inlineData.data;
          generatedImageUrl = `data:image/png;base64,${base64EncodeString}`;
        } else if (part.text) {
          generatedText = part.text;
        }
      }
    }

    if (!generatedImageUrl && !generatedText) {
      throw new Error("No content generated by the model.");
    }

    return {
      imageUrl: generatedImageUrl,
      text: generatedText
    };

  } catch (error) {
    console.error("Error generating content:", error);
    throw error;
  }
};